---
- name: Add user 'scott' to Docker group and create Docker directory
  hosts: all
  become: true
  tasks:
    - name: Ensure the docker group exists
      group:
        name: docker
        state: present

    - name: Add user 'scott' to the docker group
      user:
        name: scott
        groups: docker
        append: yes




