---
collections:
  - community.general

- hosts: all
  become: true  # Required for sudo commands

  tasks:
    - name: Add Docker's official GPG key
      block:
        - name: Update apt package index
          apt:
            update_cache: yes

        - name: Install ca-certificates and curl
          apt:
            name:
              - ca-certificates
              - curl
            state: present

        - name: Create /etc/apt/keyrings directory
          file:
            path: /etc/apt/keyrings
            state: directory
            mode: '0755'

        - name: Download Docker GPG key
          curl:
            url: https://download.docker.com/linux/ubuntu/gpg
            out: /etc/apt/keyrings/docker.asc
            force: yes  # Overwrite if exists

        - name: Set permissions on the Docker GPG key
          file:
            path: /etc/apt/keyrings/docker.asc
            mode: '0644' # a+r is equivalent to 0644
      become: true  # Ensure these tasks run with sudo

    - name: Add the repository to Apt sources
      block:
        - name: Get Ubuntu codename
          shell: ". /etc/os-release && echo \"${UBUNTU_CODENAME:-$VERSION_CODENAME}\""
          register: ubuntu_codename

        - name: Add Docker repository to apt sources list
          copy:
            dest: /etc/apt/sources.list.d/docker.list
            content: |
              deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ubuntu_codename.stdout }} stable
          become: true

        - name: Update apt package index again after adding the repository
          apt:
            update_cache: yes
      become: true # Ensure these tasks run with sudo

