---
- hosts: all  # Target hosts - change if needed (e.g., webservers)
  become: true # Required for installing packages

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
     
    - name: Install qemu-guest-agent
      apt:
        name: qemu-guest-agent
        state: present
     
    - name: Install nfs-common
      apt:
        name: nfs-common
        state: present
      
    - name: Install apache2-utils
      apt:
        name: apache2-utils
        state: present
    
    - name: Install cockpit
      apt:
        name: cockpit
        state: present
        # Optional: Start and enable Cockpit service (if needed)
