---
- name: Install Docker on Ubuntu 24.04
  hosts: all
  become: true
  tasks:
    - name: Add Docker's official GPG key
      shell: |
        sudo apt-get update
        sudo apt-get install -y ca-certificates curl
        sudo install -m 0755 -d /etc/apt/keyrings
        sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
        sudo chmod a+r /etc/apt/keyrings/docker.asc

    - name: Add the Docker repository to Apt sources
      shell: |
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo \"${UBUNTU_CODENAME:-$VERSION_CODENAME}\") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

    - name: Update Apt package index
      apt:
        update_cache: yes

    - name: Install Docker CE and containerd.io
      apt:
        name:
          - docker-ce
          - docker-compose-plugin
          - containerd.io
        state: present
        update_cache: no # Already updated in previous task

    - name: Verify Docker installation (optional)
      shell: docker --version
      register: docker_version
      changed_when: false  # Don't report as changed if only checking version

    - name: Print Docker Version (optional)
      debug:
        msg: "Docker version: {{ docker_version.stdout }}"

