---
- hosts: all
  become: true
  tasks:
    - name: Install Docker CE dependencies
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Add Docker's official GPG key (if not already added)
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
        update_cache: true

    - name: Update apt cache (after adding repo)
      apt:
        update_cache: yes

    - name: Install Docker CE, CLI, containerd.io, buildx plugin and compose plugin
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Enable Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Restart Docker service (to ensure everything is loaded)
      systemd:
        name: docker
        state: restarted
