---
- hosts: all
  become: true
  tasks:
    - name: Install Docker CE dependencies
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Add GPG Key for Docker Repo (Modern Approach)
      become: true
      shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpgkey > /tmp/docker.gpg
        apt-key add /tmp/docker.gpg
      args:
        creates: /etc/apt/trusted.gpg

    # Clean up temporary file (if used)
    - name: Remove Temporary GPG Key File
      file:
        path: /tmp/docker.gpg
        state: absent

    - name: Update apt cache (after adding repo)
      apt:
        update_cache: yes

    - name: Install Docker CE, CLI, containerd.io, buildx plugin and compose plugin
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Enable Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Restart Docker service (to ensure everything is loaded)
      systemd:
        name: docker
        state: restarted
